# Generated by Django 4.2.7 on 2023-11-21 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eb349947-82f8-4a77-943d-151626d69ce9')),
        ),
    ]
