# Generated by Django 4.2.7 on 2023-11-21 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_uuid_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d89a5ac-5c6a-4d12-a229-cac6abc52eb8'), unique=True),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.AddField(
            model_name='codigo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
