# Generated by Django 4.2.7 on 2023-11-21 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_codigo_alter_usuario_uuid_delete_code_codigo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a0f9587-c950-442b-b536-0da5dfa9294c'), unique=True),
        ),
    ]
